# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8c3ec7bee130315be725d813c9b6b44ec67837c56b2ff9a88e2ce07b4447cbaae70871ad74b68e72602e41a0a679f36b1d54428705ef6e83342a5bf775f8a34

test:
  secret_key_base: 195e6604944e9eb1201e51ed8e559876c0b57ef32feb041fb9d159ab1b23630cd1c18fb114777becaec994cc7c4702648fb4f166075f2afeea634e5c1bafe725

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
